//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplex.svc_simplex {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametroFase1", Namespace="http://schemas.datacontract.org/2004/07/TP_Simplex_Azure")]
    [System.SerializableAttribute()]
    public partial class ParametroFase1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultvaloresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultvalores {
            get {
                return this.resultvaloresField;
            }
            set {
                if ((object.ReferenceEquals(this.resultvaloresField, value) != true)) {
                    this.resultvaloresField = value;
                    this.RaisePropertyChanged("resultvalores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svc_simplex.ISimplex")]
    public interface ISimplex {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/Calcular", ReplyAction="http://tempuri.org/ISimplex/CalcularResponse")]
        string Calcular(string parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/Calcular", ReplyAction="http://tempuri.org/ISimplex/CalcularResponse")]
        System.Threading.Tasks.Task<string> CalcularAsync(string parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/CalcularSimplex", ReplyAction="http://tempuri.org/ISimplex/CalcularSimplexResponse")]
        Simplex.svc_simplex.ParametroFase1 CalcularSimplex(string FO, float[] VetProdutos, string[] VetInequacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/CalcularSimplex", ReplyAction="http://tempuri.org/ISimplex/CalcularSimplexResponse")]
        System.Threading.Tasks.Task<Simplex.svc_simplex.ParametroFase1> CalcularSimplexAsync(string FO, float[] VetProdutos, string[] VetInequacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/CalculateDays", ReplyAction="http://tempuri.org/ISimplex/CalculateDaysResponse")]
        int CalculateDays(int day, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/CalculateDays", ReplyAction="http://tempuri.org/ISimplex/CalculateDaysResponse")]
        System.Threading.Tasks.Task<int> CalculateDaysAsync(int day, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarTamanhoTabela", ReplyAction="http://tempuri.org/ISimplex/SetarTamanhoTabelaResponse")]
        void SetarTamanhoTabela(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarTamanhoTabela", ReplyAction="http://tempuri.org/ISimplex/SetarTamanhoTabelaResponse")]
        System.Threading.Tasks.Task SetarTamanhoTabelaAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarValorTabela", ReplyAction="http://tempuri.org/ISimplex/SetarValorTabelaResponse")]
        void SetarValorTabela(float valor, int L, int C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarValorTabela", ReplyAction="http://tempuri.org/ISimplex/SetarValorTabelaResponse")]
        System.Threading.Tasks.Task SetarValorTabelaAsync(float valor, int L, int C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/RetornarTabela", ReplyAction="http://tempuri.org/ISimplex/RetornarTabelaResponse")]
        string RetornarTabela();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/RetornarTabela", ReplyAction="http://tempuri.org/ISimplex/RetornarTabelaResponse")]
        System.Threading.Tasks.Task<string> RetornarTabelaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarTamanhoValorVariaveis", ReplyAction="http://tempuri.org/ISimplex/SetarTamanhoValorVariaveisResponse")]
        void SetarTamanhoValorVariaveis(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarTamanhoValorVariaveis", ReplyAction="http://tempuri.org/ISimplex/SetarTamanhoValorVariaveisResponse")]
        System.Threading.Tasks.Task SetarTamanhoValorVariaveisAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarValorVariaveis", ReplyAction="http://tempuri.org/ISimplex/SetarValorVariaveisResponse")]
        void SetarValorVariaveis(string valor, int L, int C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarValorVariaveis", ReplyAction="http://tempuri.org/ISimplex/SetarValorVariaveisResponse")]
        System.Threading.Tasks.Task SetarValorVariaveisAsync(string valor, int L, int C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/RetornarValorVariaveis", ReplyAction="http://tempuri.org/ISimplex/RetornarValorVariaveisResponse")]
        string RetornarValorVariaveis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/RetornarValorVariaveis", ReplyAction="http://tempuri.org/ISimplex/RetornarValorVariaveisResponse")]
        System.Threading.Tasks.Task<string> RetornarValorVariaveisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarTamanhoMatRestricoes", ReplyAction="http://tempuri.org/ISimplex/SetarTamanhoMatRestricoesResponse")]
        void SetarTamanhoMatRestricoes(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarTamanhoMatRestricoes", ReplyAction="http://tempuri.org/ISimplex/SetarTamanhoMatRestricoesResponse")]
        System.Threading.Tasks.Task SetarTamanhoMatRestricoesAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarMatRestricoes", ReplyAction="http://tempuri.org/ISimplex/SetarMatRestricoesResponse")]
        void SetarMatRestricoes(float valor, int L, int C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/SetarMatRestricoes", ReplyAction="http://tempuri.org/ISimplex/SetarMatRestricoesResponse")]
        System.Threading.Tasks.Task SetarMatRestricoesAsync(float valor, int L, int C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/RetornarMatRestricoes", ReplyAction="http://tempuri.org/ISimplex/RetornarMatRestricoesResponse")]
        string RetornarMatRestricoes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/RetornarMatRestricoes", ReplyAction="http://tempuri.org/ISimplex/RetornarMatRestricoesResponse")]
        System.Threading.Tasks.Task<string> RetornarMatRestricoesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/RetornarValorMatRestricoes", ReplyAction="http://tempuri.org/ISimplex/RetornarValorMatRestricoesResponse")]
        float RetornarValorMatRestricoes(int L, int C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/RetornarValorMatRestricoes", ReplyAction="http://tempuri.org/ISimplex/RetornarValorMatRestricoesResponse")]
        System.Threading.Tasks.Task<float> RetornarValorMatRestricoesAsync(int L, int C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/RetornarTamMatRestricoes", ReplyAction="http://tempuri.org/ISimplex/RetornarTamMatRestricoesResponse")]
        int RetornarTamMatRestricoes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplex/RetornarTamMatRestricoes", ReplyAction="http://tempuri.org/ISimplex/RetornarTamMatRestricoesResponse")]
        System.Threading.Tasks.Task<int> RetornarTamMatRestricoesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimplexChannel : Simplex.svc_simplex.ISimplex, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexClient : System.ServiceModel.ClientBase<Simplex.svc_simplex.ISimplex>, Simplex.svc_simplex.ISimplex {
        
        public SimplexClient() {
        }
        
        public SimplexClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Calcular(string parametro) {
            return base.Channel.Calcular(parametro);
        }
        
        public System.Threading.Tasks.Task<string> CalcularAsync(string parametro) {
            return base.Channel.CalcularAsync(parametro);
        }
        
        public Simplex.svc_simplex.ParametroFase1 CalcularSimplex(string FO, float[] VetProdutos, string[] VetInequacao) {
            return base.Channel.CalcularSimplex(FO, VetProdutos, VetInequacao);
        }
        
        public System.Threading.Tasks.Task<Simplex.svc_simplex.ParametroFase1> CalcularSimplexAsync(string FO, float[] VetProdutos, string[] VetInequacao) {
            return base.Channel.CalcularSimplexAsync(FO, VetProdutos, VetInequacao);
        }
        
        public int CalculateDays(int day, int month, int year) {
            return base.Channel.CalculateDays(day, month, year);
        }
        
        public System.Threading.Tasks.Task<int> CalculateDaysAsync(int day, int month, int year) {
            return base.Channel.CalculateDaysAsync(day, month, year);
        }
        
        public void SetarTamanhoTabela(int x, int y) {
            base.Channel.SetarTamanhoTabela(x, y);
        }
        
        public System.Threading.Tasks.Task SetarTamanhoTabelaAsync(int x, int y) {
            return base.Channel.SetarTamanhoTabelaAsync(x, y);
        }
        
        public void SetarValorTabela(float valor, int L, int C) {
            base.Channel.SetarValorTabela(valor, L, C);
        }
        
        public System.Threading.Tasks.Task SetarValorTabelaAsync(float valor, int L, int C) {
            return base.Channel.SetarValorTabelaAsync(valor, L, C);
        }
        
        public string RetornarTabela() {
            return base.Channel.RetornarTabela();
        }
        
        public System.Threading.Tasks.Task<string> RetornarTabelaAsync() {
            return base.Channel.RetornarTabelaAsync();
        }
        
        public void SetarTamanhoValorVariaveis(int x, int y) {
            base.Channel.SetarTamanhoValorVariaveis(x, y);
        }
        
        public System.Threading.Tasks.Task SetarTamanhoValorVariaveisAsync(int x, int y) {
            return base.Channel.SetarTamanhoValorVariaveisAsync(x, y);
        }
        
        public void SetarValorVariaveis(string valor, int L, int C) {
            base.Channel.SetarValorVariaveis(valor, L, C);
        }
        
        public System.Threading.Tasks.Task SetarValorVariaveisAsync(string valor, int L, int C) {
            return base.Channel.SetarValorVariaveisAsync(valor, L, C);
        }
        
        public string RetornarValorVariaveis() {
            return base.Channel.RetornarValorVariaveis();
        }
        
        public System.Threading.Tasks.Task<string> RetornarValorVariaveisAsync() {
            return base.Channel.RetornarValorVariaveisAsync();
        }
        
        public void SetarTamanhoMatRestricoes(int x, int y) {
            base.Channel.SetarTamanhoMatRestricoes(x, y);
        }
        
        public System.Threading.Tasks.Task SetarTamanhoMatRestricoesAsync(int x, int y) {
            return base.Channel.SetarTamanhoMatRestricoesAsync(x, y);
        }
        
        public void SetarMatRestricoes(float valor, int L, int C) {
            base.Channel.SetarMatRestricoes(valor, L, C);
        }
        
        public System.Threading.Tasks.Task SetarMatRestricoesAsync(float valor, int L, int C) {
            return base.Channel.SetarMatRestricoesAsync(valor, L, C);
        }
        
        public string RetornarMatRestricoes() {
            return base.Channel.RetornarMatRestricoes();
        }
        
        public System.Threading.Tasks.Task<string> RetornarMatRestricoesAsync() {
            return base.Channel.RetornarMatRestricoesAsync();
        }
        
        public float RetornarValorMatRestricoes(int L, int C) {
            return base.Channel.RetornarValorMatRestricoes(L, C);
        }
        
        public System.Threading.Tasks.Task<float> RetornarValorMatRestricoesAsync(int L, int C) {
            return base.Channel.RetornarValorMatRestricoesAsync(L, C);
        }
        
        public int RetornarTamMatRestricoes() {
            return base.Channel.RetornarTamMatRestricoes();
        }
        
        public System.Threading.Tasks.Task<int> RetornarTamMatRestricoesAsync() {
            return base.Channel.RetornarTamMatRestricoesAsync();
        }
    }
}
